# Generated by Django 4.0.6 on 2022-08-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='kode_penerbangan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='barang',
            name='tujuan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='barang',
            name='tanggal',
            field=models.CharField(max_length=100),
        ),
    ]
